## Analyse de critique de film


Analyse de la base (valeurs manquantes, base équilibrée...)

In [2]:
import pandas as pd
data_train = pd.read_csv('train.csv', usecols = [1,2])
data_test = pd.read_csv('test.csv', usecols = [1,2])

In [3]:
data_train

                                                 reviews  label
0      For a movie that gets no respect there sure ar...      1
1      Bizarre horror movie filled with famous faces ...      1
2      A solid, if unremarkable film. Matthau, as Ein...      1
3      It's a strange feeling to sit alone in a theat...      1
4      You probably all already know this by now, but...      1
...                                                  ...    ...
24995  My comments may be a bit of a spoiler, for wha...      0
24996  The "saucy" misadventures of four au pairs who...      0
24997  Oh, those Italians! Assuming that movies about...      0
24998  Eight academy nominations? It's beyond belief....      0
24999  Not that I dislike childrens movies, but this ...      0

[25000 rows x 2 columns]

In [4]:
data_test

# bon réflexe serait de mélanger lignes !
# on utilise Shuffle pour le faire
# ici on fait RF donc c'est vrai que ça change rien

                                                 reviews  label
0      Based on an actual story, John Boorman shows t...      1
1      This is a gem. As a Film Four production - the...      1
2      I really like this show. It has drama, romance...      1
3      This is the best 3-D experience Disney has at ...      1
4      Of the Korean movies I've seen, only three had...      1
...                                                  ...    ...
24995  With actors like Depardieu and Richard it is r...      0
24996  If you like to get a couple of fleeting glimps...      0
24997  When something can be anything you want it to ...      0
24998  I had heard good things about "States of Grace...      0
24999  Well, this movie actually did have one redeemi...      0

[25000 rows x 2 columns]

In [6]:
data_test.label.unique()
data_train.label.unique()

array([1, 0])

In [7]:
data_train.isna().sum()
data_test.isna().sum()

reviews    0
label      0
dtype: int64

In [8]:
# On regarde si base train equilibré par rapport au label
ones = [el for el in data_train['label'] if el==1]
zeros = [el for el in data_train['label'] if el==0]
print(len(ones))
print(len(zeros))

# totalement équilibrée ici

12500
12500

In [9]:
# On regarde si base train equilibré par rapport au label
ones = [el for el in data_test['label'] if el==1]
zeros = [el for el in data_test['label'] if el==0]
print(len(ones))
print(len(zeros))

# totalement équilibrée ici

12500
12500

Nettoyage du texte en retirant les stop-words. 
Création d'une nouvelle colonne contenant le texte nettoyé. 
On utilise nltk pour l'ensemble des stop words.

In [10]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [11]:
stop_words = set(stopwords.words('english'))

In [12]:
word_tokens = data_train["reviews"].apply(lambda x : " ".join([word for word in word_tokenize(str(x)) if word not in stop_words]))

In [13]:
word_tokens

0        For movie gets respect sure lot memorable quot...
1        Bizarre horror movie filled famous faces stole...
2        A solid , unremarkable film . Matthau , Einste...
3        It 's strange feeling sit alone theater occupi...
4        You probably already know , 5 additional episo...
                               ...
24995    My comments may bit spoiler , 's worth . Stop ...
24996    The `` saucy '' misadventures four au pairs ar...
24997    Oh , Italians ! Assuming movies aristocrats we...
24998    Eight academy nominations ? It 's beyond belie...
24999    Not I dislike childrens movies , tearjerker re...
Name: reviews, Length: 25000, dtype: object

In [14]:
data_train["new_reviews"] = word_tokens
data_train

,reviews,label,new_reviews
0,For a movie that gets no respect there sure ar...,1,For movie gets respect sure lot memorable quot...
1,Bizarre horror movie filled with famous faces ...,1,Bizarre horror movie filled famous faces stole...
2,"A solid, if unremarkable film. Matthau, as Ein...",1,"A solid , unremarkable film . Matthau , Einste..."
3,It's a strange feeling to sit alone in a theat...,1,It 's strange feeling sit alone theater occupi...
4,"You probably all already know this by now, but...",1,"You probably already know , 5 additional episo..."
...,...,...,...
24995,"My comments may be a bit of a spoiler, for wha...",0,"My comments may bit spoiler , 's worth . Stop ..."
24996,"The ""saucy"" misadventures of four au pairs who...",0,The `` saucy '' misadventures four au pairs ar...
24997,"Oh, those Italians! Assuming that movies about...",0,"Oh , Italians ! Assuming movies aristocrats we..."
24998,Eight academy nominations? It's beyond belief....,0,Eight academy nominations ? It 's beyond belie...
24999,"Not that I dislike childrens movies, but this ...",0,"Not I dislike childrens movies , tearjerker re..."

In [15]:

word_tokens2 = data_test["reviews"].apply(lambda x : " ".join([word for word in word_tokenize(str(x)) if word not in stop_words]))

In [16]:
data_test["new_reviews"] = word_tokens2

Application de BagOfWords (CountVectorizer) et de TF-IDF (TfidfVectorizer) sur les 10 premières lignes (à l'échelle du mot).

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = data_train["new_reviews"][0:10]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X

<10x725 sparse matrix of type '<class 'numpy.int64'>'
	with 854 stored elements in Compressed Sparse Row format>

In [18]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 2]
 [0 0 0 ... 0 0 0]]

In [19]:
print(vectorizer.get_feature_names())

['10', '1935', 'abc', 'absolute', 'according', 'accuracy', 'acted', 'actors', 'actually', 'adam', 'addition', 'additional', 'admit', 'advent', 'again', 'agent', 'agreed', 'aired', 'alan', 'all', 'alone', 'already', 'also', 'alter', 'although', 'amazed', 'among', 'and', 'anew', 'angelo', 'anger', 'another', 'antagonizes', 'anya', 'anything', 'apparent', 'appropriate', 'as', 'ashenden', 'at', 'attempted', 'author', 'axis', 'aylmer', 'baby', 'backgrounds', 'badmitton', 'bank', 'based', 'beautiful', 'beautifully', 'befuddlement', 'begins', 'behind', 'believe', 'best', 'bet', 'bets', 'better', 'beverly', 'bike', 'billy', 'birdie', 'bizarre', 'blind', 'bob', 'boiled', 'book', 'boys', 'br', 'break', 'bring', 'brooklyn', 'brother', 'brothers', 'brought', 'brownstone', 'bully', 'burgess', 'business', 'but', 'butter', 'buying', 'canceled', 'captured', 'carlos', 'caseman', 'chain', 'chaperoning', 'character', 'characters', 'charming', 'children', 'china', 'christened', 'church', 'clever', 'closer', 'coda', 'com', 'combination', 'come', 'comforted', 'comic', 'comments', 'complicating', 'conclusions', 'consumed', 'continued', 'conversation', 'cooking', 'cool', 'could', 'couple', 'course', 'crackerjack', 'creep', 'creepy', 'crew', 'crime', 'cristina', 'cross', 'cruise', 'cultural', 'cultures', 'culver', 'currie', 'custodial', 'damian', 'dandy', 'dark', 'databases', 'daunting', 'day', 'dealing', 'death', 'deborah', 'deeply', 'delight', 'delightful', 'describe', 'detective', 'diabolical', 'dick', 'difficulties', 'dilemmas', 'dilly', 'directed', 'director', 'disapproving', 'discovered', 'disease', 'disgusting', 'diversifying', 'dog', 'doing', 'dolman', 'downbeat', 'draws', 'dream', 'dubbed', 'dvd', 'each', 'earlier', 'east', 'easy', 'eat', 'eats', 'ego', 'eight', 'einstein', 'eli', 'end', 'ending', 'ends', 'engaged', 'enjoy', 'enliven', 'entertainingly', 'entertainment', 'episodes', 'erica', 'erupting', 'especially', 'essentially', 'even', 'ever', 'evil', 'ewww', 'ex', 'exactly', 'exaggerate', 'exorcist', 'exotic', 'eye', 'eyes', 'face', 'faces', 'fake', 'family', 'famous', 'fancies', 'fantastically', 'farrelly', 'favorite', 'favourite', 'feeling', 'feet', 'felix', 'felt', 'fictional', 'fifth', 'fifty', 'fighter', 'filled', 'film', 'films', 'finally', 'finds', 'finlay', 'fires', 'first', 'flamingo', 'flaws', 'floor', 'follow', 'for', 'forrester', 'frail', 'freckled', 'freedom', 'fried', 'friendly', 'friends', 'full', 'fun', 'funny', 'further', 'gasps', 'gateway', 'gem', 'genius', 'gets', 'giant', 'give', 'given', 'global', 'go', 'gone', 'good', 'grade', 'grader', 'grandchild', 'great', 'grey', 'grown', 'guarding', 'gummy', 'hale', 'handful', 'harrison', 'hater', 'hayter', 'he', 'health', 'hear', 'hears', 'hearty', 'heavily', 'hefty', 'heights', 'hell', 'here', 'hero', 'his', 'hitchcock', 'holds', 'hope', 'hopefully', 'hordern', 'horrible', 'horror', 'hot', 'how', 'huntley', 'hurts', 'hyde', 'hyperbolize', 'if', 'illness', 'imagine', 'imdb', 'immediately', 'in', 'including', 'incredible', 'inhabited', 'innovation', 'insecurities', 'insisting', 'instead', 'intellectual', 'internal', 'international', 'introduces', 'investments', 'involved', 'irascible', 'ironic', 'issues', 'it', 'james', 'jean', 'jeffrey', 'jewelry', 'job', 'joe', 'john', 'joke', 'jr', 'kathleen', 'keen', 'kelada', 'kid', 'kids', 'kill', 'kills', 'kinky', 'know', 'konvitz', 'last', 'later', 'latter', 'laugh', 'laura', 'laurie', 'lawful', 'leaders', 'learn', 'leave', 'lesson', 'let', 'level', 'life', 'like', 'liked', 'likes', 'listed', 'live', 'living', 'll', 'long', 'longest', 'looked', 'lot', 'love', 'loved', 'lovely', 'made', 'mae', 'make', 'maker', 'makes', 'making', 'man', 'manager', 'marinated', 'market', 'mate', 'matthau', 'mature', 'maugham', 'maureen', 'max', 'meal', 'meeting', 'meets', 'membership', 'memorable', 'meredith', 'message', 'met', 'michael', 'microwaving', 'middle', 'miles', 'model', 'modeling', 'money', 'months', 'mood', 'moroni', 'mothers', 'mounts', 'moved', 'moves', 'movie', 'moving', 'moynahan', 'mr', 'ms', 'mundane', 'music', 'must', 'my', 'nambla', 'name', 'natural', 'nearly', 'need', 'neighbors', 'never', 'nevertheless', 'new', 'news', 'next', 'nigel', 'no', 'non', 'occasion', 'occupied', 'of', 'off', 'often', 'omg', 'once', 'one', 'opening', 'or', 'organism', 'overbearing', 'overused', 'pal', 'parents', 'part', 'patient', 'patrick', 'pawns', 'pay', 'payoff', 'peacekeeping', 'peanut', 'people', 'perfect', 'perfectly', 'perhaps', 'personally', 'perspective', 'physicists', 'pickwick', 'piece', 'piscopo', 'play', 'played', 'playing', 'plays', 'plot', 'pm', 'poindexter', 'point', 'poison', 'police', 'pollination', 'popular', 'possibly', 'powerful', 'pregnancy', 'pretty', 'priest', 'probably', 'prolonged', 'proper', 'prospect', 'prosperous', 'proxy', 'pubescent', 'punched', 'quality', 'quandaries', 'quartet', 'quiet', 'quotes', 'radioactive', 'raffin', 'raines', 'raise', 'rated', 'rather', 'raymond', 're', 'reading', 'real', 'realize', 'really', 'reasons', 'record', 'redemption', 'regarding', 'register', 'reluctantly', 'remarkable', 'rennie', 'repercussions', 'resembles', 'respect', 'respected', 'response', 'retrieve', 'ring', 'rises', 'road', 'robbins', 'rockwell', 'roland', 'role', 'roles', 'rollicking', 'room', 'rosemary', 'rumored', 'sad', 'samuel', 'sandwich', 'sanitorium', 'sauce', 'saved', 'savvy', 'saw', 'say', 'scene', 'scenes', 'schooling', 'scotsman', 'scrat', 'scream', 'seas', 'second', 'seconds', 'secret', 'see', 'seemed', 'segment', 'seller', 'sense', 'sensitive', 'sentinel', 'serious', 'seven', 'sgt', 'shed', 'ship', 'shirts', 'shocks', 'shop', 'short', 'shot', 'show', 'showed', 'showmanship', 'shown', 'shows', 'shrek', 'signature', 'silently', 'simmons', 'sit', 'situation', 'skill', 'skipper', 'slated', 'sleeveless', 'slightly', 'slime', 'slimy', 'slot', 'small', 'smile', 'smuggling', 'snob', 'so', 'soared', 'solid', 'someone', 'something', 'somewhat', 'soon', 'sound', 'splashy', 'spooky', 'spotted', 'spread', 'spring', 'spy', 'squashed', 'stakes', 'stapleton', 'start', 'starts', 'state', 'stealer', 'steamship', 'steven', 'still', 'stolen', 'stomach', 'store', 'stores', 'stories', 'story', 'storyteller', 'strange', 'suburban', 'successful', 'suicides', 'suited', 'superb', 'sure', 'surrounded', 'swearing', 'sweaters', 'sylvia', 'tear', 'tears', 'television', 'tell', 'tells', 'ten', 'tendency', 'terms', 'thanks', 'that', 'the', 'theater', 'theatre', 'then', 'there', 'thermos', 'thing', 'things', 'this', 'thomas', 'thought', 'thoughtfully', 'threatening', 'three', 'thrives', 'throws', 'ticket', 'time', 'to', 'tobacco', 'toddler', 'top', 'touch', 'town', 'transformation', 'trio', 'trip', 'tv', 'two', 'type', 'typical', 'ultra', 'uncontrollably', 'understanding', 'unintentional', 'unity', 'unleashes', 'unremarkable', 'unstable', 'up', 'upon', 'us', 'use', 'using', 'valuable', 'values', 've', 'verger', 'versions', 'vicar', 'viewed', 'viewing', 'vomitous', 'votes', 'waited', 'wallach', 'war', 'wars', 'watch', 'watched', 'watches', 'watching', 'way', 'welcome', 'well', 'what', 'when', 'whining', 'whit', 'white', 'whole', 'wicked', 'wife', 'wilfred', 'wily', 'win', 'winner', 'with', 'within', 'wo', 'woman', 'wonder', 'wonderful', 'wonderfully', 'word', 'world', 'worms', 'worth', 'would', 'writer', 'written', 'years', 'you', 'young']

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer2 = TfidfVectorizer()
Y = vectorizer2.fit_transform(corpus)
print(Y.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.04616168 0.         ... 0.         0.         0.09232335]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [21]:
print(vectorizer2.get_feature_names())

['10', '1935', 'abc', 'absolute', 'according', 'accuracy', 'acted', 'actors', 'actually', 'adam', 'addition', 'additional', 'admit', 'advent', 'again', 'agent', 'agreed', 'aired', 'alan', 'all', 'alone', 'already', 'also', 'alter', 'although', 'amazed', 'among', 'and', 'anew', 'angelo', 'anger', 'another', 'antagonizes', 'anya', 'anything', 'apparent', 'appropriate', 'as', 'ashenden', 'at', 'attempted', 'author', 'axis', 'aylmer', 'baby', 'backgrounds', 'badmitton', 'bank', 'based', 'beautiful', 'beautifully', 'befuddlement', 'begins', 'behind', 'believe', 'best', 'bet', 'bets', 'better', 'beverly', 'bike', 'billy', 'birdie', 'bizarre', 'blind', 'bob', 'boiled', 'book', 'boys', 'br', 'break', 'bring', 'brooklyn', 'brother', 'brothers', 'brought', 'brownstone', 'bully', 'burgess', 'business', 'but', 'butter', 'buying', 'canceled', 'captured', 'carlos', 'caseman', 'chain', 'chaperoning', 'character', 'characters', 'charming', 'children', 'china', 'christened', 'church', 'clever', 'closer', 'coda', 'com', 'combination', 'come', 'comforted', 'comic', 'comments', 'complicating', 'conclusions', 'consumed', 'continued', 'conversation', 'cooking', 'cool', 'could', 'couple', 'course', 'crackerjack', 'creep', 'creepy', 'crew', 'crime', 'cristina', 'cross', 'cruise', 'cultural', 'cultures', 'culver', 'currie', 'custodial', 'damian', 'dandy', 'dark', 'databases', 'daunting', 'day', 'dealing', 'death', 'deborah', 'deeply', 'delight', 'delightful', 'describe', 'detective', 'diabolical', 'dick', 'difficulties', 'dilemmas', 'dilly', 'directed', 'director', 'disapproving', 'discovered', 'disease', 'disgusting', 'diversifying', 'dog', 'doing', 'dolman', 'downbeat', 'draws', 'dream', 'dubbed', 'dvd', 'each', 'earlier', 'east', 'easy', 'eat', 'eats', 'ego', 'eight', 'einstein', 'eli', 'end', 'ending', 'ends', 'engaged', 'enjoy', 'enliven', 'entertainingly', 'entertainment', 'episodes', 'erica', 'erupting', 'especially', 'essentially', 'even', 'ever', 'evil', 'ewww', 'ex', 'exactly', 'exaggerate', 'exorcist', 'exotic', 'eye', 'eyes', 'face', 'faces', 'fake', 'family', 'famous', 'fancies', 'fantastically', 'farrelly', 'favorite', 'favourite', 'feeling', 'feet', 'felix', 'felt', 'fictional', 'fifth', 'fifty', 'fighter', 'filled', 'film', 'films', 'finally', 'finds', 'finlay', 'fires', 'first', 'flamingo', 'flaws', 'floor', 'follow', 'for', 'forrester', 'frail', 'freckled', 'freedom', 'fried', 'friendly', 'friends', 'full', 'fun', 'funny', 'further', 'gasps', 'gateway', 'gem', 'genius', 'gets', 'giant', 'give', 'given', 'global', 'go', 'gone', 'good', 'grade', 'grader', 'grandchild', 'great', 'grey', 'grown', 'guarding', 'gummy', 'hale', 'handful', 'harrison', 'hater', 'hayter', 'he', 'health', 'hear', 'hears', 'hearty', 'heavily', 'hefty', 'heights', 'hell', 'here', 'hero', 'his', 'hitchcock', 'holds', 'hope', 'hopefully', 'hordern', 'horrible', 'horror', 'hot', 'how', 'huntley', 'hurts', 'hyde', 'hyperbolize', 'if', 'illness', 'imagine', 'imdb', 'immediately', 'in', 'including', 'incredible', 'inhabited', 'innovation', 'insecurities', 'insisting', 'instead', 'intellectual', 'internal', 'international', 'introduces', 'investments', 'involved', 'irascible', 'ironic', 'issues', 'it', 'james', 'jean', 'jeffrey', 'jewelry', 'job', 'joe', 'john', 'joke', 'jr', 'kathleen', 'keen', 'kelada', 'kid', 'kids', 'kill', 'kills', 'kinky', 'know', 'konvitz', 'last', 'later', 'latter', 'laugh', 'laura', 'laurie', 'lawful', 'leaders', 'learn', 'leave', 'lesson', 'let', 'level', 'life', 'like', 'liked', 'likes', 'listed', 'live', 'living', 'll', 'long', 'longest', 'looked', 'lot', 'love', 'loved', 'lovely', 'made', 'mae', 'make', 'maker', 'makes', 'making', 'man', 'manager', 'marinated', 'market', 'mate', 'matthau', 'mature', 'maugham', 'maureen', 'max', 'meal', 'meeting', 'meets', 'membership', 'memorable', 'meredith', 'message', 'met', 'michael', 'microwaving', 'middle', 'miles', 'model', 'modeling', 'money', 'months', 'mood', 'moroni', 'mothers', 'mounts', 'moved', 'moves', 'movie', 'moving', 'moynahan', 'mr', 'ms', 'mundane', 'music', 'must', 'my', 'nambla', 'name', 'natural', 'nearly', 'need', 'neighbors', 'never', 'nevertheless', 'new', 'news', 'next', 'nigel', 'no', 'non', 'occasion', 'occupied', 'of', 'off', 'often', 'omg', 'once', 'one', 'opening', 'or', 'organism', 'overbearing', 'overused', 'pal', 'parents', 'part', 'patient', 'patrick', 'pawns', 'pay', 'payoff', 'peacekeeping', 'peanut', 'people', 'perfect', 'perfectly', 'perhaps', 'personally', 'perspective', 'physicists', 'pickwick', 'piece', 'piscopo', 'play', 'played', 'playing', 'plays', 'plot', 'pm', 'poindexter', 'point', 'poison', 'police', 'pollination', 'popular', 'possibly', 'powerful', 'pregnancy', 'pretty', 'priest', 'probably', 'prolonged', 'proper', 'prospect', 'prosperous', 'proxy', 'pubescent', 'punched', 'quality', 'quandaries', 'quartet', 'quiet', 'quotes', 'radioactive', 'raffin', 'raines', 'raise', 'rated', 'rather', 'raymond', 're', 'reading', 'real', 'realize', 'really', 'reasons', 'record', 'redemption', 'regarding', 'register', 'reluctantly', 'remarkable', 'rennie', 'repercussions', 'resembles', 'respect', 'respected', 'response', 'retrieve', 'ring', 'rises', 'road', 'robbins', 'rockwell', 'roland', 'role', 'roles', 'rollicking', 'room', 'rosemary', 'rumored', 'sad', 'samuel', 'sandwich', 'sanitorium', 'sauce', 'saved', 'savvy', 'saw', 'say', 'scene', 'scenes', 'schooling', 'scotsman', 'scrat', 'scream', 'seas', 'second', 'seconds', 'secret', 'see', 'seemed', 'segment', 'seller', 'sense', 'sensitive', 'sentinel', 'serious', 'seven', 'sgt', 'shed', 'ship', 'shirts', 'shocks', 'shop', 'short', 'shot', 'show', 'showed', 'showmanship', 'shown', 'shows', 'shrek', 'signature', 'silently', 'simmons', 'sit', 'situation', 'skill', 'skipper', 'slated', 'sleeveless', 'slightly', 'slime', 'slimy', 'slot', 'small', 'smile', 'smuggling', 'snob', 'so', 'soared', 'solid', 'someone', 'something', 'somewhat', 'soon', 'sound', 'splashy', 'spooky', 'spotted', 'spread', 'spring', 'spy', 'squashed', 'stakes', 'stapleton', 'start', 'starts', 'state', 'stealer', 'steamship', 'steven', 'still', 'stolen', 'stomach', 'store', 'stores', 'stories', 'story', 'storyteller', 'strange', 'suburban', 'successful', 'suicides', 'suited', 'superb', 'sure', 'surrounded', 'swearing', 'sweaters', 'sylvia', 'tear', 'tears', 'television', 'tell', 'tells', 'ten', 'tendency', 'terms', 'thanks', 'that', 'the', 'theater', 'theatre', 'then', 'there', 'thermos', 'thing', 'things', 'this', 'thomas', 'thought', 'thoughtfully', 'threatening', 'three', 'thrives', 'throws', 'ticket', 'time', 'to', 'tobacco', 'toddler', 'top', 'touch', 'town', 'transformation', 'trio', 'trip', 'tv', 'two', 'type', 'typical', 'ultra', 'uncontrollably', 'understanding', 'unintentional', 'unity', 'unleashes', 'unremarkable', 'unstable', 'up', 'upon', 'us', 'use', 'using', 'valuable', 'values', 've', 'verger', 'versions', 'vicar', 'viewed', 'viewing', 'vomitous', 'votes', 'waited', 'wallach', 'war', 'wars', 'watch', 'watched', 'watches', 'watching', 'way', 'welcome', 'well', 'what', 'when', 'whining', 'whit', 'white', 'whole', 'wicked', 'wife', 'wilfred', 'wily', 'win', 'winner', 'with', 'within', 'wo', 'woman', 'wonder', 'wonderful', 'wonderfully', 'word', 'world', 'worms', 'worth', 'would', 'writer', 'written', 'years', 'you', 'young']

In [22]:
vectorizer3 = CountVectorizer(max_df = 0.9, min_df = 0.5)
Z = vectorizer3.fit_transform(corpus)
print(vectorizer3.get_feature_names())
vectorizer4 = TfidfVectorizer(max_df = 0.9, min_df = 0.5)
ZZ = vectorizer4.fit_transform(corpus)
print(vectorizer4.get_feature_names())

['film', 'movie', 'the']
['film', 'movie', 'the']

In [23]:
X_train = data_train.new_reviews
y_train = data_train.label
X_test = data_test.new_reviews
y_test = data_test.copy().label

Utilisation du modèle random forest pour apprendre le modèle permettant de détecter le caractère positif ou négatif de la critique. On construit 2 pipelines (un pour chaque encodeur de texte).

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
pipel = Pipeline([("count", CountVectorizer()), ("rf", RandomForestClassifier(n_estimators = 100))])
pipel.fit(X_train, y_train)
y_pred = pipel.predict(X_test)
y_pred
print(mean_squared_error(y_test, y_pred).sum())

0.14752

In [27]:
pipel2 = Pipeline([("tfidf", TfidfVectorizer()), ("rf", RandomForestClassifier(n_estimators = 100))])
pipel2.fit(X_train, y_train)
y_pred2 = pipel2.predict(X_test)
y_pred2
print(mean_squared_error(y_test, y_pred2).sum())

0.1518

On choisit le pipeline 2 et on calcule le features importance du modèle appris.

In [28]:
imp =pd.Series(pipel2.steps[1][1].feature_importances_ ,index=pipel2.steps[0][1].get_feature_names()).sort_values(ascending = False)
imp.head(20)

bad          0.011344
worst        0.009140
great        0.007909
waste        0.006048
awful        0.005142
even         0.004284
terrible     0.004029
plot         0.004020
boring       0.003796
excellent    0.003767
best         0.003760
nothing      0.003757
stupid       0.003476
wonderful    0.003330
horrible     0.003319
love         0.003250
movie        0.003180
worse        0.003091
perfect      0.002927
minutes      0.002871
dtype: float64

In [29]:
pipel2.steps[0][1].get_feature_names()

['00',
 '000',
 '0000000000001',
 '00001',
 '00015',
 '000s',
 '001',
 '003830',
 '006',
 '007',
 '0079',
 '0080',
 '0083',
 '0093638',
 '00am',
 '00pm',
 '00s',
 '01',
 '01pm',
 '02',
 '020410',
 '029',
 '03',
 '04',
 '041',
 '05',
 '050',
 '06',
 '06th',
 '07',
 '08',
 '087',
 '089',
 '08th',
 '09',
 '0f',
 '0ne',
 '0r',
 '0s',
 '10',
 '100',
 '1000',
 '1000000',
 '10000000000000',
 '1000lb',
 '1000s',
 '1001',
 '100b',
 '100k',
 '100m',
 '100min',
 '100mph',
 '100s',
 '100th',
 '100x',
 '100yards',
 '101',
 '101st',
 '102',
 '102nd',
 '103',
 '104',
 '1040',
 '1040a',
 '1040s',
 '105',
 '1050',
 '105lbs',
 '106',
 '106min',
 '107',
 '108',
 '109',
 '10am',
 '10lines',
 '10mil',
 '10min',
 '10minutes',
 '10p',
 '10pm',
 '10s',
 '10star',
 '10th',
 '10x',
 '10yr',
 '11',
 '110',
 '1100',
 '11001001',
 '1100ad',
 '111',
 '112',
 '1138',
 '114',
 '1146',
 '115',
 '116',
 '117',
 '11f',
 '11m',
 '11th',
 '12',
 '120',
 '1200',
 '1200f',
 '1201',
 '1202',
 '123',
 '12383499143743701',
 '125',
 '125m',
 '127',
 '128',
 '12a',
 '12hr',
 '12m',
 '12mm',
 '12s',
 '12th',
 '13',
 '130',
 '1300',
 '1300s',
 '131',
 '1318',
 '132',
 '134',
 '135',
 '135m',
 '136',
 '137',
 '138',
 '139',
 '13k',
 '13s',
 '13th',
 '14',
 '140',
 '1408',
 '140hp',
 '1415',
 '142',
 '145',
 '1454',
 '146',
 '147',
 '1473',
 '149',
 '1492',
 '14a',
 '14ieme',
 '14s',
 '14th',
 '14yr',
 '14ème',
 '15',
 '150',
 '1500',
 '1500s',
 '150_worst_cases_of_nepotism',
 '150k',
 '150m',
 '151',
 '152',
 '153',
 '1547',
 '155',
 '156',
 '1561',
 '157',
 '158',
 '1594',
 '15mins',
 '15minutes',
 '15s',
 '15th',
 '16',
 '160',
 '1600',
 '1600s',
 '160lbs',
 '161',
 '1610',
 '163',
 '164',
 '165',
 '166',
 '1660s',
 '168',
 '169',
 '1692',
 '16ieme',
 '16k',
 '16mm',
 '16s',
 '16th',
 '16x9',
 '16ème',
 '16éme',
 '17',
 '170',
 '1700',
 '1700s',
 '1701',
 '171',
 '175',
 '177',
 '1775',
 '1780s',
 '1790s',
 '1794',
 '1798',
 '17million',
 '17th',
 '18',
 '180',
 '1800',
 '1800mph',
 '1800s',
 '1801',
 '1805',
 '1809',
 '180d',
 '1812',
 '1813',
 '18137',
 '1814',
 '1816',
 '1820',
 '1824',
 '183',
 '1830',
 '1832',
 '1836',
 '1837',
 '1838',
 '1839',
 '1840',
 '1840s',
 '1844',
 '1846',
 '1847',
 '185',
 '1850',
 '1850ies',
 '1850s',
 '1852',
 '1853',
 '1854',
 '1855',
 '1859',
 '1860',
 '1860s',
 '1861',
 '1862',
 '1863',
 '1864',
 '1865',
 '1870',
 '1870s',
 '1871',
 '1873',
 '1874',
 '1875',
 '1876',
 '188',
 '1880',
 '1880s',
 '1881',
 '1886',
 '1887',
 '1888',
 '1889',
 '188o',
 '1890',
 '1890s',
 '1892',
 '1893',
 '1894',
 '1895',
 '1896',
 '1897',
 '1898',
 '1899',
 '18a',
 '18s',
 '18th',
 '18year',
 '19',
 '190',
 '1900',
 '1900s',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '1910',
 '1910s',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '192',
 '1920',
 '1920ies',
 '1920s',
 '1921',
 '1922',
 '1923',
 '1924',
 '1925',
 '1926',
 '1927',
 '1928',
 '1929',
 '1930',
 '1930ies',
 '1930s',
 '1931',
 '1932',
 '1933',
 '1934',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '193o',
 '194',
 '1940',
 '1940s',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1948',
 '1949',
 '1949er',
 '195',
 '1950',
 '1950s',
 '1951',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1961',
 '1961s',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '197',
 '1970',
 '1970ies',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '19796',
 '197o',
 '1980',
 '1980ies',
 '1980s',
 '1981',
 '1982',
 '1982s',
 '1983',
 '1983s',
 '1984',
 '1984ish',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19k',
 '19th',
 '19thc',
 '1am',
 '1and',
 '1d',
 '1h',
 '1h30',
 '1h40',
 '1h40m',
 '1h53',
 '1hour',
 '1hr',
 '1million',
 '1min',
 '1mln',
 '1o',
 '1s',
 '1st',
 '1ton',
 '1tv',
 '1½',
 '1ç',
 '20',
 '200',
 '2000',
 '20000',
 '20001',
 '2000ad',
 '2000s',
 '2001',
 '2002',
 '2003',
 '2004',
 '2004s',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '200ft',
 '200th',
 '201',
 '2010',
 '2012',
 '2013',
 '2015',
 '2017',
 '2019',
 '2020',
 '2022',
 '2023',
 '2030',
 '2031',
 '2033',
 '2035',
 '2036',
 '2038',
 '204',
 '2040',
 '2044',
 '2046',
 '2047',
 '2050',
 '2053',
 '2054',
 '206',
 '2060',
 '2070',
 '2080',
 '209',
 '2090',
 '20c',
 '20ft',
 '20k',
 '20m',
 '20mins',
 '20minutes',
 '20mn',
 '20p',
 '20perr',
 '20s',
 '20th',
 '20ties',
 '20widow',
 '20x',
 '20year',
 '20yrs',
 '21',
 '210',
 '2100',
 '214',
 '215',
 '2151',
 '216',
 '21699',
 '21849889',
 '21849890',
 '21849907',
 '21st',
 '22',
 '220',
 '2200',
 '221',
 '2210',
 '22101',
 '222',
 '223',
 '225',
 '2257',
 '225mins',
 '227',
 '22d',
 '22h45',
 '22nd',
 '23',
 '230lbs',
 '230mph',
 '231',
 '232',
 '233',
 '236',
 '237',
 '23d',
 '23rd',
 '24',
 '240',
 '2400',
 '241',
 '242',
 '248',
 '2480',
 '249',
 '24m30s',
 '24th',
 '24years',
 '25',
 '250',
 '2500',
 '250000',
 '25million',
 '25mins',
 '25s',
 '25th',
 '25yo',
 '25yrs',
 '26',
 '260',
 '2600',
 '261k',
 '262',
 '2642',
 '269',
 '26th',
 '27',
 '270',
 '272',
 '273',
 '274',
 '275',
 '2772',
 '278',
 '27th',
 '27x41',
 '28',
 '280',
 '285',
 '28th',
 '29',
 '29th',
 '2am',
 '2d',
 '2fast',
 '2furious',
 '2h',
 '2h30',
 '2hour',
 '2hours',
 '2hr',
 '2hrs',
 '2in',
 '2inch',
 '2k',
 '2more',
 '2nd',
 '2oo4',
 '2oo5',
 '2pac',
 '2point4',
 '2s',
 '2x4',
 '30',
 '300',
 '3000',
 '300ad',
 '300c',
 '300lbs',
 '300mln',
 '3012',
 '303',
 '305',
 '30am',
 '30ish',
 '30k',
 '30lbs',
 '30min',
 '30mins',
 '30pm',
 '30s',
 '30something',
 '30th',
 '30ties',
 '31',
 '3199',
 '31st',
 '32',
 '3200',
 '320x180',
 '32lb',
 '32nd',
 '33',
 '330am',
 '330mins',
 '332960073452',
 '336th',
 '33m',
 '34',
 '345',
 '3462',
 '34th',
 '35',
 '350',
 '3500',
 '3516',
 '356',
 '357',
 '35c',
 '35mins',
 '35mm',
 '35pm',
 '35th',
 '35yr',
 '36',
 '360',
 '365',
 '36th',
 '37',
 '370',
 '372',
 '378',
 '38',
 '38k',
 '38th',
 '39',
 '395',
 '39th',
 '3am',
 '3bs',
 '3d',
 '3dvd',
 '3k',
 '3lbs',
 '3m',
 '3mins',
 '3p',
 '3p0',
 '3pm',
 '3po',
 '3rd',
 '3rds',
 '3th',
 '3who',
 '3x5',
 '3yrs',
 '40',
 '400',
 '4000',
 '401k',
 '405',
 '409',
 '40am',
 '40min',
 '40mins',
 '40mph',
 '40s',
 '40th',
 '41',
 '42',
 '420',
 '425',
 '428',
 '42nd',
 '43',
 '430',
 '44',
 '440',
 '442nd',
 '44c',
 '44yrs',
 '45',
 '450',
 '4500',
 '451',
 '454',
 '45am',
 '45min',
 '45mins',
 '45s',
 '46',
 '465',
 '469',
 '47',
 '475',
 '477',
 '47s',
 '48',
 '480m',
 '480p',
 '48hrs',
 '49',
 '498',
 '49th',
 '4am',
 '4cylinder',
 '4d',
 '4eva',
 '4ever',
 '4f',
 '4h',
 '4hrs',
 '4k',
 '4kids',
 '4m',
 '4o',
 '4pm',
 '4th',
 '4w',
 '4ward',
 '4x',
 '4x4',
 '50',
 '500',
 '5000',
 '500000',
 '500ad',
 '500db',
 '500lbs',
 '502',
 '50c',
 '50ft',
 '50ies',
 '50ish',
 '50k',
 '50min',
 '50mins',
 '50s',
 '50th',
 '50usd',
 '51',
 '51b',
 '51st',
 '52',
 '5200',
 '5250',
 '529',
 '52s',
 '53',
 '53m',
 '54',
 '5400',
 '540i',
 '54th',
 '55',
 '5539',
 '555',
 '55th',
 '56',
 '57',
 '571',
 '576',
 '578',
 '57d',
 '58',
 '58th',
 '59',
 '598947',
 '59th',
 '5hrs',
 '5ive',
 '5kph',
 '5million',
 '5min',
 '5mins',
 '5s',
 '5seconds',
 '5th',
 '5x',
 '5x5',
 '5years',
 '5yo',
 '5yrs',
 '60',
 '600',
 '6000',
 '607',
 '608',
 '60ies',
 '60ish',
 '60mph',
 '60s',
 '60th',
 '60ties',
 '61',
 '618',
 '62',
 '6200',
 '62229249',
 '63',
 '637',
 '63rd',
 '64',
 '65',
 '65m',
 '66',
 '660',
 '666',
 '66er',
 '67',
 '6723',
 '67th',
 '68',
 '68th',
 '69',
 '69th',
 '6am',
 '6b',
 '6ft',
 '6hours',
 '6k',
 '6million',
 '6pm',
 '6th',
 '6wks',
 '6yo',
 '70',
 '700',
 '701',
 '707',
 '70ies',
 '70m',
 '70mm',
 '70s',
 '70th',
 '71',
 '713',
 '72',
 '72nd',
 '73',
 '7300',
 '735',
 '737',
 '74',
 '740',
 '740il',
 '747',
 '747s',
 '74th',
 '75',
 '750',
 '75054',
 '75c',
 '75m',
 '76',
 '7600',
 '77',
 '78',
 '788',
 '78rpm',
 '79',
 '79th',
 '7days',
 '7even',
 '7eventy',
 '7ft',
 '7ish',
 '7mm',
 '7th',
 '7½th',
 '80',
 '800',
 '8000',
 '80ies',
 '80ish',
 '80min',
 '80s',
 '80yr',
 '81',
 '817',
 '819',
 '82',
 '820',
 '8217',
 '8230',
 '83',
 '84',
 '849',
 '84f',
 '84s',
 '85',
 '850',
 '850pm',
 '86',
 '86s',
 '87',
 '8700',
 '8763',
 '878',
 '87minutes',
 '88',
 '88min',
 '89',
 '89or',
 '89s',
 '8bit',
 '8ftdf',
 '8k',
 '8mm',
 '8o',
 '8p',
 '8pm',
 '8star',
 '8th',
 '8u',
 '8½',
 '90',
 '900',
 '9000',
 '90210',
 '905',
 '90c',
 '90ish',
 '90min',
 '90mins',
 '90s',
 '91',
 '911',
 '914',
 '917',
 '92',
 '921',
 '92fs',
 '92nd',
 '93',
 '937',
 '94',
 '9484',
 '94s',
 '94th',
 '95',
 '950',
 '95th',
 '96',
 '97',
 '970',
 '974th',
 '978',
 '98',
 '987',
 '98minutes',
 '99',
 '998',
 '999',
 '9999',
 '99cents',
 '99p',
 '99½',
 '9_',
 '9am',
 '9as',
 '9do',
 '9ers',
 '9is',
 '9lbs',
 '9mm',
 ...]

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred2))

0.85248
0.8482